#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : sphinxcontrib-spelling
Version  : 5.1.2
Release  : 15
URL      : https://files.pythonhosted.org/packages/b6/42/f62b01ffefaa529c32f3f433b6979d418beaf631aa2346df03c6a376d718/sphinxcontrib-spelling-5.1.2.tar.gz
Source0  : https://files.pythonhosted.org/packages/b6/42/f62b01ffefaa529c32f3f433b6979d418beaf631aa2346df03c6a376d718/sphinxcontrib-spelling-5.1.2.tar.gz
Summary  : Sphinx spelling extension
Group    : Development/Tools
License  : BSD-2-Clause
Requires: sphinxcontrib-spelling-license = %{version}-%{release}
Requires: sphinxcontrib-spelling-python = %{version}-%{release}
Requires: sphinxcontrib-spelling-python3 = %{version}-%{release}
Requires: Sphinx
Requires: flake8
BuildRequires : Sphinx
BuildRequires : buildreq-distutils3
BuildRequires : flake8
BuildRequires : pbr
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pyenchant
BuildRequires : pytest
BuildRequires : tox
BuildRequires : virtualenv

%description
=========================
         sphinxcontrib-spelling
        =========================
        
        This package contains sphinxcontrb.spelling, a spelling checker for
        Sphinx-based documentation.  It uses PyEnchant_ to produce a report
        showing misspelled words.
        
        Refer to the `main documentation page

%package license
Summary: license components for the sphinxcontrib-spelling package.
Group: Default

%description license
license components for the sphinxcontrib-spelling package.


%package python
Summary: python components for the sphinxcontrib-spelling package.
Group: Default
Requires: sphinxcontrib-spelling-python3 = %{version}-%{release}

%description python
python components for the sphinxcontrib-spelling package.


%package python3
Summary: python3 components for the sphinxcontrib-spelling package.
Group: Default
Requires: python3-core
Provides: pypi(sphinxcontrib_spelling)
Requires: pypi(pyenchant)
Requires: pypi(sphinx)

%description python3
python3 components for the sphinxcontrib-spelling package.


%prep
%setup -q -n sphinxcontrib-spelling-5.1.2
cd %{_builddir}/sphinxcontrib-spelling-5.1.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1592855314
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}$(python -c "import sys; print(sys.path[-1])") python setup.py test || :
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/sphinxcontrib-spelling
cp %{_builddir}/sphinxcontrib-spelling-5.1.2/LICENSE %{buildroot}/usr/share/package-licenses/sphinxcontrib-spelling/22c50971a614a37b4b2ca0c412ea7f3235b7a975
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/sphinxcontrib-spelling/22c50971a614a37b4b2ca0c412ea7f3235b7a975

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
