#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x3B6D06A0C428437A (doug@doughellmann.com)
#
Name     : sphinxcontrib-spelling
Version  : 5.0.0
Release  : 11
URL      : https://files.pythonhosted.org/packages/62/a8/f52b1d2bc2012ad1fe4b81be19d88f543bce258074902b7ac5b18a13dda5/sphinxcontrib-spelling-5.0.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/62/a8/f52b1d2bc2012ad1fe4b81be19d88f543bce258074902b7ac5b18a13dda5/sphinxcontrib-spelling-5.0.0.tar.gz
Source1  : https://files.pythonhosted.org/packages/62/a8/f52b1d2bc2012ad1fe4b81be19d88f543bce258074902b7ac5b18a13dda5/sphinxcontrib-spelling-5.0.0.tar.gz.asc
Summary  : Sphinx spelling extension
Group    : Development/Tools
License  : BSD-2-Clause
Requires: sphinxcontrib-spelling-license = %{version}-%{release}
Requires: sphinxcontrib-spelling-python = %{version}-%{release}
Requires: sphinxcontrib-spelling-python3 = %{version}-%{release}
Requires: Sphinx
Requires: flake8
Requires: six
BuildRequires : Sphinx
BuildRequires : buildreq-distutils3
BuildRequires : flake8
BuildRequires : pbr
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pyenchant
BuildRequires : pytest
BuildRequires : six
BuildRequires : tox
BuildRequires : virtualenv

%description
=========================
sphinxcontrib-spelling
=========================
This package contains sphinxcontrb.spelling, a spelling checker for
Sphinx-based documentation.  It uses PyEnchant_ to produce a report
showing misspelled words.

%package license
Summary: license components for the sphinxcontrib-spelling package.
Group: Default

%description license
license components for the sphinxcontrib-spelling package.


%package python
Summary: python components for the sphinxcontrib-spelling package.
Group: Default
Requires: sphinxcontrib-spelling-python3 = %{version}-%{release}

%description python
python components for the sphinxcontrib-spelling package.


%package python3
Summary: python3 components for the sphinxcontrib-spelling package.
Group: Default
Requires: python3-core
Provides: pypi(sphinxcontrib_spelling)
Requires: pypi(six)
Requires: pypi(sphinx)
Requires: pypi(pyenchant)

%description python3
python3 components for the sphinxcontrib-spelling package.


%prep
%setup -q -n sphinxcontrib-spelling-5.0.0
cd %{_builddir}/sphinxcontrib-spelling-5.0.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1587068710
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}$(python -c "import sys; print(sys.path[-1])") python setup.py test || :
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/sphinxcontrib-spelling
cp %{_builddir}/sphinxcontrib-spelling-5.0.0/LICENSE %{buildroot}/usr/share/package-licenses/sphinxcontrib-spelling/22c50971a614a37b4b2ca0c412ea7f3235b7a975
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/sphinxcontrib-spelling/22c50971a614a37b4b2ca0c412ea7f3235b7a975

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
